In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Tables ##

In [2]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [3]:
cones.show(3)

In [4]:
cones.show()

In [5]:
# Creates a new table with only the selected column
flavor_table = cones.select('Flavor')

In [6]:
# Notice the old table is unmodified
cones.show()
flavor_table.show()

In [7]:
# Since we did not store this anywhere, we can see the output but cannot use it for anything
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [8]:
# The old table is unmodified (and the 'Flavor'/'Price' one is lost)
cones.show()

In [9]:
# Creates a new table with the specified column missing
cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [10]:
cones.show()

In [11]:
cones_without_price = cones.drop('Price')
cones_without_price

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [12]:
# Selects all rows where 'Flavor' is equal to 'chocolate'
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [13]:
# Sorts the table by price
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [14]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [15]:
cones.sort('Flavor', descending=True)

Flavor     | Color       | Price
strawberry | pink        | 3.55
strawberry | pink        | 5.25
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [16]:
# You can reuse variable names when you need to make multiple edits.
chocolate_table = cones.where('Flavor', 'chocolate')
chocolate_table = chocolate_table.drop('Flavor')
chocolate_table.show()

### Practice

Starting with the original cones table, create a new table by performing the following steps:
1. Select all the rows where the color is pink.
2. Drop the color column.
3. Sort by price in descending order.

### A more interesting table

In [17]:
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [19]:
point_guards = nba.where('position', 'PG')
point_guards_2020 = point_guards.where('season', 2020)

In [20]:
point_guards_2020.show(10)

In [21]:
point_guards.num_rows

1475

In [22]:
point_guards_2020.num_rows

82

In [23]:
point_guards_2020 = point_guards_2020.drop('position')

In [24]:
# We forgot to assign the table in the previous cell to a variable
point_guards_2020

rank | name              | team                   | salary   | season
1    | Stephen Curry     | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | Houston Rockets        | 38506482 | 2020
4    | John Wall         | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [25]:
# Now our changed table is stored in point_guards
point_guards_2020 = point_guards_2020.drop('rank', 'position', 'season')
point_guards_2020.show(10)

In [26]:
# Here's another way to get the columns you want by directly selecting them
point_guards_alt = nba.where('position', 'PG').where('season', 2020)
point_guards_alt = point_guards_alt.select('name', 'team', 'salary')
point_guards_alt.show(10)

In [27]:
point_guards_2020.sort('salary').show(10)

In [28]:
point_guards_2020.sort('salary', descending=True).show(10)

### Practice

In the year 2001, who was the highest paid player for the Los Angeles Lakers?

In [ ]:
kldnvsnvrnpinewhhhhhoahfowehgg

In [ ]:
season2001 = nba.where('season', 2001)
lakers2001 = season2001.where('team', 'Los Angeles Lakers')
lakers2001Salary = lakers2001.sort('salary', descending = True)
lakers2001Salary.show(1)

In [41]:
lakers_2001 = nba.where('season', 2001).where('team', 'Los Angeles Lakers')
lakers_2001.show(1)